<ScreenManagement>:
    PaginaInicial:
    LabelConfig:
    Introducao:
    A02:
    A03:
    A04:
    A05:
    A06:
    A07:
    A08:
 
<PaginaInicial>:
    name: 'paginaInicial'
    BoxLayout:
        orientation: 'vertical'

        Button:
            on_release: app.root.switch_to_introducao()
            text: 'Introdução'
        Button:
            on_release: app.root.switch_to_A02()
            text: 'Como Preparar Adubo Orgânico 1 - Composto Granulado'
        Button:
            on_release: app.root.switch_to_A03()
            text: 'Como Preparar Adubo Orgânico 2 - Torta de Mamona'
        Button:
            on_release: app.root.switch_to_A04()
            text: 'Como Preparar Adubo Orgânico 3 - Composteira Caseira'
        Button:
            on_release: app.root.switch_to_A05()
            text: 'Como Preparar Adubo Orgânico 4 - Composto Líquido'
        Button:
            on_release: app.root.switch_to_A06()
            text: 'Comece a Plantar Hoje! - Girassol'
        Button:
            on_release: app.root.switch_to_A07()
            text: 'Paisagismo Para Ambiente Interno'
        Button:
            on_release: app.root.switch_to_A08()
            text: 'Uso de Lampadas Incandecentes Para Paisagismo Sustentável'
 
<Introducao>:
    name: 'introducao'
     
    BoxLayout:
        orientation: 'vertical'
 
        Label:
            text: 'Configurações de um  widget Label'
             
        Button:
            on_release: app.root.switch_to_paginaInicial()
            text: 'Retorno'

<A02>:
    name: 'A02'
     
    BoxLayout:
        orientation: 'vertical'
 
        Label:
            text: 'Configurações de um  widget Label'
             
        Button:
            on_release: app.root.switch_to_paginaInicial()
            text: 'Retorno'

<A03>:
    name: 'A03'
     
    BoxLayout:
        orientation: 'vertical'
 
        Label:
            text: 'Configurações de um  widget Label'
             
        Button:
            on_release: app.root.switch_to_paginaInicial()
            text: 'Retorno'

<A04>:
    name: 'A04'
     
    BoxLayout:
        orientation: 'vertical'
 
        Label:
            text: 'Configurações de um  widget Label'
             
        Button:
            on_release: app.root.switch_to_paginaInicial()
            text: 'Retorno'

<A05>:
    name: 'A05'
     
    BoxLayout:
        orientation: 'vertical'
 
        Label:
            text: 'Configurações de um  widget Label'
             
        Button:
            on_release: app.root.switch_to_paginaInicial()
            text: 'Retorno'

<A06>:
    name: 'A06'
     
    BoxLayout:
        orientation: 'vertical'
 
        Label:
            text: 'Configurações de um  widget Label'
             
        Button:
            on_release: app.root.switch_to_paginaInicial()
            text: 'Retorno'

<A07>:
    name: 'A07'
     
    BoxLayout:
        orientation: 'vertical'
 
        Label:
            text: 'Configurações de um  widget Label'
             
        Button:
            on_release: app.root.switch_to_paginaInicial()
            text: 'Retorno'

<A08>:
    name: 'A08'
     
    BoxLayout:
        orientation: 'vertical'
 
        Label:
            text: 'Configurações de um  widget Label'
             
        Button:
            on_release: app.root.switch_to_paginaInicial()
            text: 'Retorno'